version: '3.9'

services:
  gateway:
    build: 
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      AUTH_ADDR: auth-service:8081
      ASSET_ADDR: asset-service:8082
      MARKET_ADDR: market-service:8083
      TRADING_ADDR: trading-service:8084
      JWT_SECRET: my-secret-key-for-course-project
    depends_on:
      - auth-service

  auth-service:
    build: 
      context: .
      dockerfile: ./services/auth/Dockerfile
    ports:
      - "8081:8081"
    environment:
      PORT: "8081"
      DB_DSN: postgres://myuser:vova123@postgres:5432/maindb?sslmode=disable
      JWT_SECRET: my-secret-key-for-course-project
    depends_on:
      migrate:
        condition: service_completed_successfully

  market-service:
    build:
      context: .
      dockerfile: ./services/market/Dockerfile
    ports:
      - "8083:8083"
    environment:
      PORT: "8083"
      DB_DSN: postgres://myuser:vova123@postgres:5432/maindb?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      migrate:
        condition: service_completed_successfully

  trading-service:
    build:
      context: .
      dockerfile: ./services/trading/Dockerfile
    ports:
      - "8084:8084"
    environment:
      PORT: "8084"
      DB_DSN: postgres://myuser:vova123@postgres:5432/maindb?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully

  asset-service:
    build:
      context: .
      dockerfile: ./services/asset/Dockerfile
    ports:
      - "8082:8082"
    environment:
      PORT: "8082"
      DB_DSN: postgres://myuser:vova123@postgres:5432/maindb?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully

  redis:
    image: redis:7-alpine
    ports: 
      - "6379:6379"

  ws-hub:
    build:
      context: .
      dockerfile: ./services/ws_hub/Dockerfile
    ports: 
      - "8085:8085"
    environment:
      PORT: "8085"
      REDIS_ADDR: redis:6379
    depends_on:
      - redis

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: vova123
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d maindb"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate 
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://myuser:vova123@postgres:5432/maindb?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  seed:
    build:
      context: .
      dockerfile: ./cmd/seed/Dockerfile
    environment:
      DB_DSN: postgres://myuser:vova123@postgres:5432/maindb?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: "no"

volumes:
  postgres_data: