// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: trading/trading.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioRequest) Reset() {
	*x = GetPortfolioRequest{}
	mi := &file_trading_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioRequest) ProtoMessage() {}

func (x *GetPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{0}
}

func (x *GetPortfolioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PortfolioItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssetId           string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity          string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AvgBuyPrice       string                 `protobuf:"bytes,4,opt,name=avg_buy_price,json=avgBuyPrice,proto3" json:"avg_buy_price,omitempty"`
	CurrentPrice      string                 `protobuf:"bytes,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	TotalValue        string                 `protobuf:"bytes,6,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	ProfitLoss        string                 `protobuf:"bytes,7,opt,name=profit_loss,json=profitLoss,proto3" json:"profit_loss,omitempty"`
	ProfitLossPercent string                 `protobuf:"bytes,8,opt,name=profit_loss_percent,json=profitLossPercent,proto3" json:"profit_loss_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PortfolioItem) Reset() {
	*x = PortfolioItem{}
	mi := &file_trading_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioItem) ProtoMessage() {}

func (x *PortfolioItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioItem.ProtoReflect.Descriptor instead.
func (*PortfolioItem) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioItem) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PortfolioItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PortfolioItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PortfolioItem) GetAvgBuyPrice() string {
	if x != nil {
		return x.AvgBuyPrice
	}
	return ""
}

func (x *PortfolioItem) GetCurrentPrice() string {
	if x != nil {
		return x.CurrentPrice
	}
	return ""
}

func (x *PortfolioItem) GetTotalValue() string {
	if x != nil {
		return x.TotalValue
	}
	return ""
}

func (x *PortfolioItem) GetProfitLoss() string {
	if x != nil {
		return x.ProfitLoss
	}
	return ""
}

func (x *PortfolioItem) GetProfitLossPercent() string {
	if x != nil {
		return x.ProfitLossPercent
	}
	return ""
}

type PortfolioResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*PortfolioItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalValueUsdt  string                 `protobuf:"bytes,2,opt,name=total_value_usdt,json=totalValueUsdt,proto3" json:"total_value_usdt,omitempty"`
	BalanceUsdt     string                 `protobuf:"bytes,3,opt,name=balance_usdt,json=balanceUsdt,proto3" json:"balance_usdt,omitempty"`
	TotalProfitLoss string                 `protobuf:"bytes,4,opt,name=total_profit_loss,json=totalProfitLoss,proto3" json:"total_profit_loss,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PortfolioResponse) Reset() {
	*x = PortfolioResponse{}
	mi := &file_trading_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioResponse) ProtoMessage() {}

func (x *PortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioResponse.ProtoReflect.Descriptor instead.
func (*PortfolioResponse) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{2}
}

func (x *PortfolioResponse) GetItems() []*PortfolioItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PortfolioResponse) GetTotalValueUsdt() string {
	if x != nil {
		return x.TotalValueUsdt
	}
	return ""
}

func (x *PortfolioResponse) GetBalanceUsdt() string {
	if x != nil {
		return x.BalanceUsdt
	}
	return ""
}

func (x *PortfolioResponse) GetTotalProfitLoss() string {
	if x != nil {
		return x.TotalProfitLoss
	}
	return ""
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_trading_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{3}
}

func (x *BuyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BuyRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *BuyRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type SellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_trading_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{4}
}

func (x *SellRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SellRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SellRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AssetSymbol   string                 `protobuf:"bytes,3,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AssetPrice    string                 `protobuf:"bytes,5,opt,name=asset_price,json=assetPrice,proto3" json:"asset_price,omitempty"`
	TotalUsdt     string                 `protobuf:"bytes,6,opt,name=total_usdt,json=totalUsdt,proto3" json:"total_usdt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_trading_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionResponse) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *TransactionResponse) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *TransactionResponse) GetAssetPrice() string {
	if x != nil {
		return x.AssetPrice
	}
	return ""
}

func (x *TransactionResponse) GetTotalUsdt() string {
	if x != nil {
		return x.TotalUsdt
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_trading_trading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TransactionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AssetSymbol   string                 `protobuf:"bytes,3,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AssetPrice    string                 `protobuf:"bytes,5,opt,name=asset_price,json=assetPrice,proto3" json:"asset_price,omitempty"`
	TotalUsdt     string                 `protobuf:"bytes,6,opt,name=total_usdt,json=totalUsdt,proto3" json:"total_usdt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionItem) Reset() {
	*x = TransactionItem{}
	mi := &file_trading_trading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItem) ProtoMessage() {}

func (x *TransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItem.ProtoReflect.Descriptor instead.
func (*TransactionItem) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionItem) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *TransactionItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *TransactionItem) GetAssetPrice() string {
	if x != nil {
		return x.AssetPrice
	}
	return ""
}

func (x *TransactionItem) GetTotalUsdt() string {
	if x != nil {
		return x.TotalUsdt
	}
	return ""
}

func (x *TransactionItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionItem     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsResponse) Reset() {
	*x = TransactionsResponse{}
	mi := &file_trading_trading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsResponse) ProtoMessage() {}

func (x *TransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsResponse.ProtoReflect.Descriptor instead.
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionsResponse) GetTransactions() []*TransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type AddBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceRequest) Reset() {
	*x = AddBalanceRequest{}
	mi := &file_trading_trading_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceRequest) ProtoMessage() {}

func (x *AddBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceRequest.ProtoReflect.Descriptor instead.
func (*AddBalanceRequest) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{9}
}

func (x *AddBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddBalanceRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BalanceUsdt   string                 `protobuf:"bytes,2,opt,name=balance_usdt,json=balanceUsdt,proto3" json:"balance_usdt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_trading_trading_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_trading_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_trading_trading_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalanceResponse) GetBalanceUsdt() string {
	if x != nil {
		return x.BalanceUsdt
	}
	return ""
}

var File_trading_trading_proto protoreflect.FileDescriptor

const file_trading_trading_proto_rawDesc = "" +
	"\n" +
	"\x15trading/trading.proto\x12\atrading\".\n" +
	"\x13GetPortfolioRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x99\x02\n" +
	"\rPortfolioItem\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\x12\"\n" +
	"\ravg_buy_price\x18\x04 \x01(\tR\vavgBuyPrice\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\tR\fcurrentPrice\x12\x1f\n" +
	"\vtotal_value\x18\x06 \x01(\tR\n" +
	"totalValue\x12\x1f\n" +
	"\vprofit_loss\x18\a \x01(\tR\n" +
	"profitLoss\x12.\n" +
	"\x13profit_loss_percent\x18\b \x01(\tR\x11profitLossPercent\"\xba\x01\n" +
	"\x11PortfolioResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.trading.PortfolioItemR\x05items\x12(\n" +
	"\x10total_value_usdt\x18\x02 \x01(\tR\x0etotalValueUsdt\x12!\n" +
	"\fbalance_usdt\x18\x03 \x01(\tR\vbalanceUsdt\x12*\n" +
	"\x11total_profit_loss\x18\x04 \x01(\tR\x0ftotalProfitLoss\"\\\n" +
	"\n" +
	"BuyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\"]\n" +
	"\vSellRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\"\xd7\x01\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fasset_symbol\x18\x03 \x01(\tR\vassetSymbol\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x1f\n" +
	"\vasset_price\x18\x05 \x01(\tR\n" +
	"assetPrice\x12\x1d\n" +
	"\n" +
	"total_usdt\x18\x06 \x01(\tR\ttotalUsdt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"1\n" +
	"\x16GetTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd3\x01\n" +
	"\x0fTransactionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fasset_symbol\x18\x03 \x01(\tR\vassetSymbol\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x1f\n" +
	"\vasset_price\x18\x05 \x01(\tR\n" +
	"assetPrice\x12\x1d\n" +
	"\n" +
	"total_usdt\x18\x06 \x01(\tR\ttotalUsdt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"T\n" +
	"\x14TransactionsResponse\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.trading.TransactionItemR\ftransactions\"D\n" +
	"\x11AddBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"M\n" +
	"\x0fBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fbalance_usdt\x18\x02 \x01(\tR\vbalanceUsdt2\xe7\x02\n" +
	"\x0eTradingService\x12H\n" +
	"\fGetPortfolio\x12\x1c.trading.GetPortfolioRequest\x1a\x1a.trading.PortfolioResponse\x128\n" +
	"\x03Buy\x12\x13.trading.BuyRequest\x1a\x1c.trading.TransactionResponse\x12:\n" +
	"\x04Sell\x12\x14.trading.SellRequest\x1a\x1c.trading.TransactionResponse\x12Q\n" +
	"\x0fGetTransactions\x12\x1f.trading.GetTransactionsRequest\x1a\x1d.trading.TransactionsResponse\x12B\n" +
	"\n" +
	"AddBalance\x12\x1a.trading.AddBalanceRequest\x1a\x18.trading.BalanceResponseB!Z\x1fcrypto-simulator/pkg/pb/tradingb\x06proto3"

var (
	file_trading_trading_proto_rawDescOnce sync.Once
	file_trading_trading_proto_rawDescData []byte
)

func file_trading_trading_proto_rawDescGZIP() []byte {
	file_trading_trading_proto_rawDescOnce.Do(func() {
		file_trading_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_trading_proto_rawDesc), len(file_trading_trading_proto_rawDesc)))
	})
	return file_trading_trading_proto_rawDescData
}

var file_trading_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_trading_trading_proto_goTypes = []any{
	(*GetPortfolioRequest)(nil),    // 0: trading.GetPortfolioRequest
	(*PortfolioItem)(nil),          // 1: trading.PortfolioItem
	(*PortfolioResponse)(nil),      // 2: trading.PortfolioResponse
	(*BuyRequest)(nil),             // 3: trading.BuyRequest
	(*SellRequest)(nil),            // 4: trading.SellRequest
	(*TransactionResponse)(nil),    // 5: trading.TransactionResponse
	(*GetTransactionsRequest)(nil), // 6: trading.GetTransactionsRequest
	(*TransactionItem)(nil),        // 7: trading.TransactionItem
	(*TransactionsResponse)(nil),   // 8: trading.TransactionsResponse
	(*AddBalanceRequest)(nil),      // 9: trading.AddBalanceRequest
	(*BalanceResponse)(nil),        // 10: trading.BalanceResponse
}
var file_trading_trading_proto_depIdxs = []int32{
	1,  // 0: trading.PortfolioResponse.items:type_name -> trading.PortfolioItem
	7,  // 1: trading.TransactionsResponse.transactions:type_name -> trading.TransactionItem
	0,  // 2: trading.TradingService.GetPortfolio:input_type -> trading.GetPortfolioRequest
	3,  // 3: trading.TradingService.Buy:input_type -> trading.BuyRequest
	4,  // 4: trading.TradingService.Sell:input_type -> trading.SellRequest
	6,  // 5: trading.TradingService.GetTransactions:input_type -> trading.GetTransactionsRequest
	9,  // 6: trading.TradingService.AddBalance:input_type -> trading.AddBalanceRequest
	2,  // 7: trading.TradingService.GetPortfolio:output_type -> trading.PortfolioResponse
	5,  // 8: trading.TradingService.Buy:output_type -> trading.TransactionResponse
	5,  // 9: trading.TradingService.Sell:output_type -> trading.TransactionResponse
	8,  // 10: trading.TradingService.GetTransactions:output_type -> trading.TransactionsResponse
	10, // 11: trading.TradingService.AddBalance:output_type -> trading.BalanceResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_trading_trading_proto_init() }
func file_trading_trading_proto_init() {
	if File_trading_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_trading_proto_rawDesc), len(file_trading_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_trading_proto_goTypes,
		DependencyIndexes: file_trading_trading_proto_depIdxs,
		MessageInfos:      file_trading_trading_proto_msgTypes,
	}.Build()
	File_trading_trading_proto = out.File
	file_trading_trading_proto_goTypes = nil
	file_trading_trading_proto_depIdxs = nil
}
