CREATE TABLE assets(
    id UUID PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    full_name VARCHAR(50) UNIQUE NOT NULL,
    is_active BOOLEAN NOT NULL,
    initial_price DECIMAL(15,6) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
