// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: market/market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PriceUsdt     string                 `protobuf:"bytes,3,opt,name=price_usdt,json=priceUsdt,proto3" json:"price_usdt,omitempty"`
	ChangeUsdt    string                 `protobuf:"bytes,4,opt,name=change_usdt,json=changeUsdt,proto3" json:"change_usdt,omitempty"`
	ChangePercent string                 `protobuf:"bytes,5,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_market_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_market_market_proto_rawDescGZIP(), []int{0}
}

func (x *PriceUpdate) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PriceUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceUpdate) GetPriceUsdt() string {
	if x != nil {
		return x.PriceUsdt
	}
	return ""
}

func (x *PriceUpdate) GetChangeUsdt() string {
	if x != nil {
		return x.ChangeUsdt
	}
	return ""
}

func (x *PriceUpdate) GetChangePercent() string {
	if x != nil {
		return x.ChangePercent
	}
	return ""
}

func (x *PriceUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetCurrentPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPricesRequest) Reset() {
	*x = GetCurrentPricesRequest{}
	mi := &file_market_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPricesRequest) ProtoMessage() {}

func (x *GetCurrentPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPricesRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPricesRequest) Descriptor() ([]byte, []int) {
	return file_market_market_proto_rawDescGZIP(), []int{1}
}

type GetCurrentPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*PriceUpdate         `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPricesResponse) Reset() {
	*x = GetCurrentPricesResponse{}
	mi := &file_market_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPricesResponse) ProtoMessage() {}

func (x *GetCurrentPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPricesResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentPricesResponse) Descriptor() ([]byte, []int) {
	return file_market_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetCurrentPricesResponse) GetPrices() []*PriceUpdate {
	if x != nil {
		return x.Prices
	}
	return nil
}

type GetPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryRequest) Reset() {
	*x = GetPriceHistoryRequest{}
	mi := &file_market_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryRequest) ProtoMessage() {}

func (x *GetPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_market_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetPriceHistoryRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *GetPriceHistoryRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetPriceHistoryRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PricePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          string                 `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricePoint) Reset() {
	*x = PricePoint{}
	mi := &file_market_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricePoint) ProtoMessage() {}

func (x *PricePoint) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricePoint.ProtoReflect.Descriptor instead.
func (*PricePoint) Descriptor() ([]byte, []int) {
	return file_market_market_proto_rawDescGZIP(), []int{4}
}

func (x *PricePoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PricePoint) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *PricePoint) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *PricePoint) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *PricePoint) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

type GetPriceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PricePoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryResponse) Reset() {
	*x = GetPriceHistoryResponse{}
	mi := &file_market_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryResponse) ProtoMessage() {}

func (x *GetPriceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_market_market_proto_rawDescGZIP(), []int{5}
}

func (x *GetPriceHistoryResponse) GetPoints() []*PricePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_market_market_proto protoreflect.FileDescriptor

const file_market_market_proto_rawDesc = "" +
	"\n" +
	"\x13market/market.proto\x12\x06market\"\xc5\x01\n" +
	"\vPriceUpdate\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"price_usdt\x18\x03 \x01(\tR\tpriceUsdt\x12\x1f\n" +
	"\vchange_usdt\x18\x04 \x01(\tR\n" +
	"changeUsdt\x12%\n" +
	"\x0echange_percent\x18\x05 \x01(\tR\rchangePercent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\x19\n" +
	"\x17GetCurrentPricesRequest\"G\n" +
	"\x18GetCurrentPricesResponse\x12+\n" +
	"\x06prices\x18\x01 \x03(\v2\x13.market.PriceUpdateR\x06prices\"W\n" +
	"\x16GetPriceHistoryRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"z\n" +
	"\n" +
	"PricePoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\tR\x05close\"E\n" +
	"\x17GetPriceHistoryResponse\x12*\n" +
	"\x06points\x18\x01 \x03(\v2\x12.market.PricePointR\x06points2\xba\x01\n" +
	"\rMarketService\x12U\n" +
	"\x10GetCurrentPrices\x12\x1f.market.GetCurrentPricesRequest\x1a .market.GetCurrentPricesResponse\x12R\n" +
	"\x0fGetPriceHistory\x12\x1e.market.GetPriceHistoryRequest\x1a\x1f.market.GetPriceHistoryResponseB Z\x1ecrypto-simulator/pkg/pb/marketb\x06proto3"

var (
	file_market_market_proto_rawDescOnce sync.Once
	file_market_market_proto_rawDescData []byte
)

func file_market_market_proto_rawDescGZIP() []byte {
	file_market_market_proto_rawDescOnce.Do(func() {
		file_market_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_market_proto_rawDesc), len(file_market_market_proto_rawDesc)))
	})
	return file_market_market_proto_rawDescData
}

var file_market_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_market_market_proto_goTypes = []any{
	(*PriceUpdate)(nil),              // 0: market.PriceUpdate
	(*GetCurrentPricesRequest)(nil),  // 1: market.GetCurrentPricesRequest
	(*GetCurrentPricesResponse)(nil), // 2: market.GetCurrentPricesResponse
	(*GetPriceHistoryRequest)(nil),   // 3: market.GetPriceHistoryRequest
	(*PricePoint)(nil),               // 4: market.PricePoint
	(*GetPriceHistoryResponse)(nil),  // 5: market.GetPriceHistoryResponse
}
var file_market_market_proto_depIdxs = []int32{
	0, // 0: market.GetCurrentPricesResponse.prices:type_name -> market.PriceUpdate
	4, // 1: market.GetPriceHistoryResponse.points:type_name -> market.PricePoint
	1, // 2: market.MarketService.GetCurrentPrices:input_type -> market.GetCurrentPricesRequest
	3, // 3: market.MarketService.GetPriceHistory:input_type -> market.GetPriceHistoryRequest
	2, // 4: market.MarketService.GetCurrentPrices:output_type -> market.GetCurrentPricesResponse
	5, // 5: market.MarketService.GetPriceHistory:output_type -> market.GetPriceHistoryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_market_proto_init() }
func file_market_market_proto_init() {
	if File_market_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_market_proto_rawDesc), len(file_market_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_market_proto_goTypes,
		DependencyIndexes: file_market_market_proto_depIdxs,
		MessageInfos:      file_market_market_proto_msgTypes,
	}.Build()
	File_market_market_proto = out.File
	file_market_market_proto_goTypes = nil
	file_market_market_proto_depIdxs = nil
}
