// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: asset/asset.proto

package asset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	InitialPrice  float32                `protobuf:"fixed32,6,opt,name=initial_price,json=initialPrice,proto3" json:"initial_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_asset_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *Asset) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Asset) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Asset) GetInitialPrice() float32 {
	if x != nil {
		return x.InitialPrice
	}
	return 0
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_asset_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{1}
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_asset_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{2}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_asset_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialPrice  float32                `protobuf:"fixed32,1,opt,name=initial_price,json=initialPrice,proto3" json:"initial_price,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_asset_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAssetRequest) GetInitialPrice() float32 {
	if x != nil {
		return x.InitialPrice
	}
	return 0
}

func (x *CreateAssetRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateAssetRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_asset_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssetRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

type DeactivateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateAssetRequest) Reset() {
	*x = DeactivateAssetRequest{}
	mi := &file_asset_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateAssetRequest) ProtoMessage() {}

func (x *DeactivateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateAssetRequest.ProtoReflect.Descriptor instead.
func (*DeactivateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAssetRequest) Reset() {
	*x = ActivateAssetRequest{}
	mi := &file_asset_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAssetRequest) ProtoMessage() {}

func (x *ActivateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAssetRequest.ProtoReflect.Descriptor instead.
func (*ActivateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{7}
}

func (x *ActivateAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_asset_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetResponse) Reset() {
	*x = DeleteAssetResponse{}
	mi := &file_asset_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetResponse) ProtoMessage() {}

func (x *DeleteAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asset_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssetResponse) Descriptor() ([]byte, []int) {
	return file_asset_asset_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAssetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_asset_asset_proto protoreflect.FileDescriptor

const file_asset_asset_proto_rawDesc = "" +
	"\n" +
	"\x11asset/asset.proto\x12\x05asset\"\xac\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12#\n" +
	"\rinitial_price\x18\x06 \x01(\x02R\finitialPrice\"\x13\n" +
	"\x11ListAssetsRequest\":\n" +
	"\x12ListAssetsResponse\x12$\n" +
	"\x06assets\x18\x01 \x03(\v2\f.asset.AssetR\x06assets\"!\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\x12CreateAssetRequest\x12#\n" +
	"\rinitial_price\x18\x01 \x01(\x02R\finitialPrice\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\"@\n" +
	"\x12UpdateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\"(\n" +
	"\x16DeactivateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14ActivateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteAssetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb5\x03\n" +
	"\fAssetService\x12A\n" +
	"\n" +
	"ListAssets\x12\x18.asset.ListAssetsRequest\x1a\x19.asset.ListAssetsResponse\x120\n" +
	"\bGetAsset\x12\x16.asset.GetAssetRequest\x1a\f.asset.Asset\x126\n" +
	"\vCreateAsset\x12\x19.asset.CreateAssetRequest\x1a\f.asset.Asset\x126\n" +
	"\vUpdateAsset\x12\x19.asset.UpdateAssetRequest\x1a\f.asset.Asset\x12>\n" +
	"\x0fDeactivateAsset\x12\x1d.asset.DeactivateAssetRequest\x1a\f.asset.Asset\x12:\n" +
	"\rActivateAsset\x12\x1b.asset.ActivateAssetRequest\x1a\f.asset.Asset\x12D\n" +
	"\vDeleteAsset\x12\x19.asset.DeleteAssetRequest\x1a\x1a.asset.DeleteAssetResponseB\x1fZ\x1dcrypto-simulator/pkg/pb/assetb\x06proto3"

var (
	file_asset_asset_proto_rawDescOnce sync.Once
	file_asset_asset_proto_rawDescData []byte
)

func file_asset_asset_proto_rawDescGZIP() []byte {
	file_asset_asset_proto_rawDescOnce.Do(func() {
		file_asset_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_asset_proto_rawDesc), len(file_asset_asset_proto_rawDesc)))
	})
	return file_asset_asset_proto_rawDescData
}

var file_asset_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_asset_asset_proto_goTypes = []any{
	(*Asset)(nil),                  // 0: asset.Asset
	(*ListAssetsRequest)(nil),      // 1: asset.ListAssetsRequest
	(*ListAssetsResponse)(nil),     // 2: asset.ListAssetsResponse
	(*GetAssetRequest)(nil),        // 3: asset.GetAssetRequest
	(*CreateAssetRequest)(nil),     // 4: asset.CreateAssetRequest
	(*UpdateAssetRequest)(nil),     // 5: asset.UpdateAssetRequest
	(*DeactivateAssetRequest)(nil), // 6: asset.DeactivateAssetRequest
	(*ActivateAssetRequest)(nil),   // 7: asset.ActivateAssetRequest
	(*DeleteAssetRequest)(nil),     // 8: asset.DeleteAssetRequest
	(*DeleteAssetResponse)(nil),    // 9: asset.DeleteAssetResponse
}
var file_asset_asset_proto_depIdxs = []int32{
	0, // 0: asset.ListAssetsResponse.assets:type_name -> asset.Asset
	1, // 1: asset.AssetService.ListAssets:input_type -> asset.ListAssetsRequest
	3, // 2: asset.AssetService.GetAsset:input_type -> asset.GetAssetRequest
	4, // 3: asset.AssetService.CreateAsset:input_type -> asset.CreateAssetRequest
	5, // 4: asset.AssetService.UpdateAsset:input_type -> asset.UpdateAssetRequest
	6, // 5: asset.AssetService.DeactivateAsset:input_type -> asset.DeactivateAssetRequest
	7, // 6: asset.AssetService.ActivateAsset:input_type -> asset.ActivateAssetRequest
	8, // 7: asset.AssetService.DeleteAsset:input_type -> asset.DeleteAssetRequest
	2, // 8: asset.AssetService.ListAssets:output_type -> asset.ListAssetsResponse
	0, // 9: asset.AssetService.GetAsset:output_type -> asset.Asset
	0, // 10: asset.AssetService.CreateAsset:output_type -> asset.Asset
	0, // 11: asset.AssetService.UpdateAsset:output_type -> asset.Asset
	0, // 12: asset.AssetService.DeactivateAsset:output_type -> asset.Asset
	0, // 13: asset.AssetService.ActivateAsset:output_type -> asset.Asset
	9, // 14: asset.AssetService.DeleteAsset:output_type -> asset.DeleteAssetResponse
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_asset_asset_proto_init() }
func file_asset_asset_proto_init() {
	if File_asset_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_asset_proto_rawDesc), len(file_asset_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_asset_proto_goTypes,
		DependencyIndexes: file_asset_asset_proto_depIdxs,
		MessageInfos:      file_asset_asset_proto_msgTypes,
	}.Build()
	File_asset_asset_proto = out.File
	file_asset_asset_proto_goTypes = nil
	file_asset_asset_proto_depIdxs = nil
}
